name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push da imagem
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/hello-app
          TAG=$(date +%s) # timestamp único
          echo "TAG=$TAG" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Clonar repositório de manifests
        uses: actions/checkout@v3
        with:
          repository: mateoclima/hello-manifests
          token: ${{ secrets.GITHUB_TOKEN }} # ou ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Atualizar Deployment com nova imagem
        run: |
          sed -i "/name: hello-app/{n;s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ env.TAG }}|}" deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Atualizando imagem para ${{ env.TAG }}" || echo "Nenhuma alteração para commitar"
          git push
